export const bills = [
  {
    id: "0",
    description: "Salário",
    category: "4",
    category_description: "Salário",
    price: "2000.00",
    data: "20220809",
    status: "Success",
  },
  {
    id: "1",
    description: "Compras para Casa",
    category: "1",
    category_description: "Casa",
    price: "-70.25",
    data: "20220809",
    status: "Error",
  },
  {
    id: "2",
    description: "Tablet A7",
    category: "2",
    category_description: "Compras",
    price: "-113.20",
    data: "20220809",
    status: "Error",
  },
  {
    id: "3",
    description: "Macarrão",
    category: "3",
    category_description: "Glovo",
    price: "-34",
    data: "20220809",
    status: "Error",
  },
  {
    id: "4",
    description: "Strog",
    category: "3",
    category_description: "Glovo",
    price: "-34",
    data: "20220809",
    status: "Error",
  },
  {
    id: "5",
    description: "Churrasco",
    category: "3",
    category_description: "Glovo",
    price: "-34",
    data: "20220809",
    status: "Error",
  },
  {
    id: "6",
    description: "Carne",
    category: "3",
    category_description: "Glovo",
    price: "-34",
    data: "20220809",
    status: "Error",
  },
];
